#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Tretec Larm - Auto-uppdatera product_database.js med ellås
"""

import json
import re
import os
from datetime import datetime

print("=" * 60)
print("AUTO-UPPDATERA PRODUCT_DATABASE.JS MED ELLÅS")
print("=" * 60)
print()

# 1. Läs ellås-produkterna
print("📦 Läser ellås-produkter från lasgiganten_ellas_all.json...")
with open('lasgiganten_ellas_all.json', 'r', encoding='utf-8') as f:
    products = json.load(f)

print(f"✅ Hittade {len(products)} produkter")
print()

# 2. Konvertera till rätt format
print("🔄 Konverterar till Tretec-format...")
ellas_products = []

for product in products:
    ellas_product = {
        "artikelnummer": product.get('sku', ''),
        "e_nummer": "",
        "benamning": product.get('name', ''),
        "lagsta_orderantal": None,
        "rabattgrupp": "E",
        "pris": product.get('price', 0),
        "supplier": product.get('supplier', 'Låsgiganten'),
        "url": product.get('url', '')
    }
    ellas_products.append(ellas_product)

print(f"✅ Konverterade {len(ellas_products)} produkter")
print()

# 3. Kolla om product_database.js finns
if os.path.exists('product_database.js'):
    print("📄 Hittar product_database.js - läser befintlig databas...")
    
    with open('product_database.js', 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Hitta PRODUCT_DB-objektet
    match = re.search(r'const PRODUCT_DB\s*=\s*({[\s\S]*?});', content)
    
    if match:
        # Parsa befintlig databas
        db_json = match.group(1)
        try:
            existing_db = json.loads(db_json)
            print(f"✅ Befintlig databas inläst")
            print(f"   - Läsare: {len(existing_db.get('lasare', []))} produkter")
            print(f"   - Centralapparater: {len(existing_db.get('centralapparater', []))} produkter")
            print(f"   - Tillbehör: {len(existing_db.get('tillbehor', []))} produkter")
            print(f"   - Ellås (gamla): {len(existing_db.get('ellas', []))} produkter")
            print()
            
            # Uppdatera ellås
            existing_db['ellas'] = ellas_products
            
            print(f"🔄 Uppdaterar ellås-kategorin...")
            print(f"   - Ellås (nya): {len(existing_db['ellas'])} produkter")
            print()
            
            # Skapa backup
            backup_file = f'product_database_backup_{datetime.now().strftime("%Y%m%d_%H%M%S")}.js'
            print(f"💾 Skapar backup: {backup_file}")
            with open(backup_file, 'w', encoding='utf-8') as f:
                f.write(content)
            print("✅ Backup skapad")
            print()
            
            # Skriv uppdaterad databas
            new_content = f"""// Product Database - Updated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// Auto-generated by import_ellas_auto.py
const PRODUCT_DB = {json.dumps(existing_db, ensure_ascii=False, indent=2)};
"""
            
            with open('product_database.js', 'w', encoding='utf-8') as f:
                f.write(new_content)
            
            print("✅ product_database.js uppdaterad!")
            print()
            
        except json.JSONDecodeError as e:
            print(f"❌ Kunde inte parsa befintlig databas: {e}")
            print("💡 Skapar en helt ny product_database.js istället...")
            create_new = True
    else:
        print("⚠️ Kunde inte hitta PRODUCT_DB i filen")
        print("💡 Skapar en helt ny product_database.js istället...")
        create_new = True
else:
    print("⚠️ product_database.js finns inte")
    print("💡 Skapar en helt ny product_database.js...")
    create_new = True

# 4. Skapa ny databas om behövs
if 'create_new' in locals() and create_new:
    new_db = {
        "lasare": [],
        "centralapparater": [],
        "tillbehor": [],
        "ellas": ellas_products
    }
    
    new_content = f"""// Product Database - Created {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// Generated by import_ellas_auto.py
const PRODUCT_DB = {json.dumps(new_db, ensure_ascii=False, indent=2)};
"""
    
    with open('product_database.js', 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    print("✅ Ny product_database.js skapad med ellås-produkter!")
    print()

# 5. Statistik
print("=" * 60)
print("📊 SAMMANFATTNING")
print("=" * 60)
prices = [p['pris'] for p in ellas_products if p['pris']]
print(f"Antal ellås-produkter: {len(ellas_products)}")
print(f"Lägsta pris: {min(prices):.2f} kr")
print(f"Högsta pris: {max(prices):.2f} kr")
print(f"Medelpris: {sum(prices)/len(prices):.2f} kr")
print()

print("=" * 60)
print("🎉 KLART!")
print("=" * 60)
print()
print("Nästa steg:")
print("1. Starta om servern (Ctrl+C och python server_v3.py)")
print("2. Öppna systemet: http://localhost:5000")
print("3. Gå till Produkter-vyn")
print("4. Filtrera på kategori: Ellås")
print("5. Du ska nu se alla 200 produkter!")
print()
