// Product Database - Created 2026-01-15 10:24:11
// Generated by import_ellas_auto.py
const PRODUCT_DB = {
  "lasare": [],
  "centralapparater": [],
  "tillbehor": [],
  "ellas": [
    {
      "artikelnummer": "50460140",
      "e_nummer": "",
      "benamning": "Anslutningskabel 6m, för Exma Protector",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 529.4,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/anslutningskabel-6m-for-exma-protector"
    },
    {
      "artikelnummer": "10016943",
      "e_nummer": "",
      "benamning": "Anslutningskabel EA220 10m",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1117.44,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/anslutningskabel-ea220-10m"
    },
    {
      "artikelnummer": "10016944",
      "e_nummer": "",
      "benamning": "Anslutningskabel EA224 10m",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1176.25,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/anslutningskabel-ea224-10m"
    },
    {
      "artikelnummer": "10016945",
      "e_nummer": "",
      "benamning": "Anslutningskabel EA225 10m",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1176.25,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/anslutningskabel-ea225-10m"
    },
    {
      "artikelnummer": "50091092",
      "e_nummer": "",
      "benamning": "Anslutningskabel EA226 10m",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1117.44,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/anslutningskabel-ea226-10m"
    },
    {
      "artikelnummer": "50024537",
      "e_nummer": "",
      "benamning": "Anslutningskabel EA227 10m",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1214.12,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/anslutningskabel-ea227-10m"
    },
    {
      "artikelnummer": "50139358",
      "e_nummer": "",
      "benamning": "Dörrhållarmagnet 400N hållkraft FE235 med ankarplatta",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 544.92,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/dorrhallarmagnet-400n-hallkraft-fe235-med-ankarplatta"
    },
    {
      "artikelnummer": "50463535",
      "e_nummer": "",
      "benamning": "Dörrhållarmagnet DHUS-K svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 865.26,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/dorrhallarmagnet-dhus-k-svart"
    },
    {
      "artikelnummer": "50140481",
      "e_nummer": "",
      "benamning": "Elektroniskt lås DC-D105-LED svenskboxen",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 985.2,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elektroniskt-las-dc-d105-led-svenskboxen"
    },
    {
      "artikelnummer": "10012376",
      "e_nummer": "",
      "benamning": "Elslutbleck 131 24V",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10548.4,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-131-24v"
    },
    {
      "artikelnummer": "10009262",
      "e_nummer": "",
      "benamning": "Elslutbleck 160-12",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1890.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-160-12"
    },
    {
      "artikelnummer": "10009263",
      "e_nummer": "",
      "benamning": "Elslutbleck 160-24",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1910.69,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-160-24"
    },
    {
      "artikelnummer": "10009267",
      "e_nummer": "",
      "benamning": "Elslutbleck 161-24",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 2249.45,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-161-24"
    },
    {
      "artikelnummer": "50003448",
      "e_nummer": "",
      "benamning": "Elslutbleck 423 Omvänd",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 2283.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-423-omvand"
    },
    {
      "artikelnummer": "50003450",
      "e_nummer": "",
      "benamning": "Elslutbleck 443 Rättvänd kolvkontakt",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3395.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-443-rattvand-kolvkontakt"
    },
    {
      "artikelnummer": "8041081",
      "e_nummer": "",
      "benamning": "Elslutbleck 5331 24V",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 12235.92,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-5331-24v"
    },
    {
      "artikelnummer": "8041148",
      "e_nummer": "",
      "benamning": "Elslutbleck 70 24V",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3190.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-70-24v"
    },
    {
      "artikelnummer": "50000202",
      "e_nummer": "",
      "benamning": "Elslutbleck EX-91HD rättvänd 12-24V",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4633.07,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-ex-91hd-rattvand-12-24v-1"
    },
    {
      "artikelnummer": "50111835",
      "e_nummer": "",
      "benamning": "Elslutbleck Step 30 rättvänd 12V",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 2825.66,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-step-30-rattvand-12v"
    },
    {
      "artikelnummer": "50093874",
      "e_nummer": "",
      "benamning": "Elslutbleck Step 40 rättvänd/omvänd  24V kolvk",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4508.23,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-step-40-rattvand-omvand-24v-kolvk"
    },
    {
      "artikelnummer": "50129842",
      "e_nummer": "",
      "benamning": "Elslutbleck Step 48 rättvänd/omvänd  24V kolvk",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4596.67,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-step-48-rattvand-omvand-24v-kolvk"
    },
    {
      "artikelnummer": "50100939",
      "e_nummer": "",
      "benamning": "Elslutbleck Step 90 rättvänd/omvänd  24V",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4896.26,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/elslutbleck-step-90-rattvand-omvand-24v"
    },
    {
      "artikelnummer": "50109045",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL402 12-24V omvänd",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6086.66,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el402-12-24v-omvand"
    },
    {
      "artikelnummer": "50023632",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL402 12-24V rättvänd",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6407.01,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el402-12-24v-rattvand"
    },
    {
      "artikelnummer": "50023633",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL402 12-24V rättvänd kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 8414.21,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el402-12-24v-rattvand-kpl"
    },
    {
      "artikelnummer": "10014241",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL480/29",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 7951.95,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el480-29"
    },
    {
      "artikelnummer": "10014237",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL480/29 kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 9225.11,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el480-29-kpl"
    },
    {
      "artikelnummer": "10014238",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL480/35 kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 9225.11,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el480-35-kpl"
    },
    {
      "artikelnummer": "10014243",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL482/29",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6322.35,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el482-29"
    },
    {
      "artikelnummer": "10014244",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL482/35",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6322.35,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el482-35"
    },
    {
      "artikelnummer": "50457520",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL502 12-24V omvänd",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 5907.82,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el502-12-24v-omvand"
    },
    {
      "artikelnummer": "50023634",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL502 12-24V rättvänd",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6218.76,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el502-12-24v-rattvand"
    },
    {
      "artikelnummer": "50023635",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL502 12-24V rättvänd kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 8203.69,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el502-12-24v-rattvand-kpl"
    },
    {
      "artikelnummer": "10010011",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL580 kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 7546.5,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el580-kpl"
    },
    {
      "artikelnummer": "50087993",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL580-70",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 9432.29,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el580-70"
    },
    {
      "artikelnummer": "LG-LGR-0169",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL582",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3990.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el582"
    },
    {
      "artikelnummer": "10010012",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL582 kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6688.82,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el582-kpl"
    },
    {
      "artikelnummer": "50026106",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL587  Hi-O kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 7546.5,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el587-hi-o-kpl"
    },
    {
      "artikelnummer": "50104971",
      "e_nummer": "",
      "benamning": "Eltryckeslås EL981 split spindle",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10041.58,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-el981-split-spindle"
    },
    {
      "artikelnummer": "50091078",
      "e_nummer": "",
      "benamning": "Eltryckeslås PE580",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 8120.49,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-pe580"
    },
    {
      "artikelnummer": "50458181",
      "e_nummer": "",
      "benamning": "Eltryckeslås SL630 secure kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 9392.25,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-sl630-secure-kpl"
    },
    {
      "artikelnummer": "50142550",
      "e_nummer": "",
      "benamning": "Eltryckeslås Step 120 klassisk split",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6617.52,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-step-120-klassisk-split"
    },
    {
      "artikelnummer": "50462934",
      "e_nummer": "",
      "benamning": "Eltryckeslås Step 130",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 8967.82,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/eltryckeslas-step-130"
    },
    {
      "artikelnummer": "50131342",
      "e_nummer": "",
      "benamning": "Fjädervred 1084 hö",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1749.7,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/fjadervred-1084-ho"
    },
    {
      "artikelnummer": "50463124",
      "e_nummer": "",
      "benamning": "Gateway G3 RJ45",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 687.79,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/gateway-g3-rj45"
    },
    {
      "artikelnummer": "50464591",
      "e_nummer": "",
      "benamning": "Gateway G3P",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 998.58,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/gateway-g3p"
    },
    {
      "artikelnummer": "50461902",
      "e_nummer": "",
      "benamning": "Gateway Nimly Connect",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1349.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/gateway-nimly-connect"
    },
    {
      "artikelnummer": "50463138",
      "e_nummer": "",
      "benamning": "Kodlås BG2000 silver höger Kpl Dorma",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4319.7,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg2000-silver-hoger-kpl-dorma"
    },
    {
      "artikelnummer": "50463134",
      "e_nummer": "",
      "benamning": "Kodlås BG2000 silver Kpl ASSA",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4319.7,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg2000-silver-kpl-assa"
    },
    {
      "artikelnummer": "50155164",
      "e_nummer": "",
      "benamning": "Kodlås BG2000 Smart Lock v2 silver SB",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3334.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg2000-smart-lock-v2-silver-sb"
    },
    {
      "artikelnummer": "50155163",
      "e_nummer": "",
      "benamning": "Kodlås BG2000 Smart Lock v2 svart SB",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 2893.64,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg2000-smart-lock-v2-svart-sb"
    },
    {
      "artikelnummer": "50463135",
      "e_nummer": "",
      "benamning": "Kodlås BG2000 svart vänster Kpl Dorma",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4483.51,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg2000-svart-vanster-kpl-dorma"
    },
    {
      "artikelnummer": "50463131",
      "e_nummer": "",
      "benamning": "Kodlås BG4000 Nordic+ silver",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3662.21,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg4000-nordic-silver"
    },
    {
      "artikelnummer": "50463129",
      "e_nummer": "",
      "benamning": "Kodlås BG4000 Nordic+ silver Kpl ASSA",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 5085.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg4000-nordic-silver-kpl-assa"
    },
    {
      "artikelnummer": "50463130",
      "e_nummer": "",
      "benamning": "Kodlås BG4000 Nordic+ svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3777.77,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg4000-nordic-svart"
    },
    {
      "artikelnummer": "50463128",
      "e_nummer": "",
      "benamning": "Kodlås BG4000 Nordic+ svart Kpl  ASSA",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 5200.47,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg4000-nordic-svart-kpl-assa"
    },
    {
      "artikelnummer": "50001015",
      "e_nummer": "",
      "benamning": "Kodlås BG5000 för ovalcylinder svart Kpl ASSA",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4389.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg5000-for-ovalcylinder-svart-kpl-assa"
    },
    {
      "artikelnummer": "50001012",
      "e_nummer": "",
      "benamning": "Kodlås Bg5000 Silver Kpl Assa",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4292.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg5000-silver-kpl-assa"
    },
    {
      "artikelnummer": "50001009",
      "e_nummer": "",
      "benamning": "Kodlås BG5000 svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3190.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg5000-svart"
    },
    {
      "artikelnummer": "50001013",
      "e_nummer": "",
      "benamning": "Kodlås Bg5000 Svart Kpl Assa",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4389.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg5000-svart-kpl-assa"
    },
    {
      "artikelnummer": "50001011",
      "e_nummer": "",
      "benamning": "Kodlås Bg5000 Svart Kpl Dorma",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4389.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-bg5000-svart-kpl-dorma"
    },
    {
      "artikelnummer": "50463485",
      "e_nummer": "",
      "benamning": "Kodlås Code knappar RFID Ultimate svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3418.36,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-code-knappar-rfid-ultimate-svart"
    },
    {
      "artikelnummer": "50463484",
      "e_nummer": "",
      "benamning": "Kodlås Code knappar RFID Ultimate vit",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3418.36,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-code-knappar-rfid-ultimate-vit"
    },
    {
      "artikelnummer": "LG-50003095-2",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic Home silver 2-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6980.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-home-silver-2-pack"
    },
    {
      "artikelnummer": "LG-50003095-3",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic Home silver 3-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10470.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-home-silver-3-pack"
    },
    {
      "artikelnummer": "LG-50003095-4",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic Home silver 4-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 13960.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-home-silver-4-pack"
    },
    {
      "artikelnummer": "50003096",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic Home svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3490.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-home-svart"
    },
    {
      "artikelnummer": "LG-50003096-2",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic Home svart 2-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6980.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-home-svart-2-pack"
    },
    {
      "artikelnummer": "LG-50003096-3",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic Home svart 3-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10470.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-home-svart-3-pack"
    },
    {
      "artikelnummer": "LG-50003096-4",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic Home svart 4-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 13960.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-home-svart-4-pack"
    },
    {
      "artikelnummer": "50456707",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic silver",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3390.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-silver"
    },
    {
      "artikelnummer": "LG-50456707-2",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic silver 2-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6780.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-silver-2-pack"
    },
    {
      "artikelnummer": "LG-50456707-3",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic silver 3-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10170.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-silver-3-pack"
    },
    {
      "artikelnummer": "LG-50456707-4",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic silver 4-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 13560.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-silver-4-pack"
    },
    {
      "artikelnummer": "50463662",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3390.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-v2n-propack-svart"
    },
    {
      "artikelnummer": "LG-50463662-2",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic svart 2-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6780.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-svart-2-pack"
    },
    {
      "artikelnummer": "LG-50463662-3",
      "e_nummer": "",
      "benamning": "Kodlås Doorman Classic svart 3-pack",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10170.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-classic-svart-3-pack"
    },
    {
      "artikelnummer": "50001058",
      "e_nummer": "",
      "benamning": "Kodlås Doorman L3S Pro - borstat stål",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4990.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-l3s-flex-borstat-stal"
    },
    {
      "artikelnummer": "50001826",
      "e_nummer": "",
      "benamning": "Kodlås Doorman L3S Pro - svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 4990.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-doorman-l3s-flex-svart"
    },
    {
      "artikelnummer": "50461905",
      "e_nummer": "",
      "benamning": "Kodlås Touch Pro touchknappar RFID finger silver/svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3990.23,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-touch-pro-touchknappar-rfid-finger-silver-svart"
    },
    {
      "artikelnummer": "50461904",
      "e_nummer": "",
      "benamning": "Kodlås Touch Pro touchknappar RFID finger Ultimate svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3990.23,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-touch-pro-touchknappar-rfid-finger-ultimate-svart"
    },
    {
      "artikelnummer": "50461906",
      "e_nummer": "",
      "benamning": "Kodlås Touch touchknappar RFID Ultimate svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3288.28,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kodlas-touch-touchknappar-rfid-ultimate-svart"
    },
    {
      "artikelnummer": "443105",
      "e_nummer": "",
      "benamning": "Kontakt 3 polig hane",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 25.07,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kontakt-3-polig-hane"
    },
    {
      "artikelnummer": "443028",
      "e_nummer": "",
      "benamning": "Kontakt 3 polig hona",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 25.07,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kontakt-3-polig-hona"
    },
    {
      "artikelnummer": "443333",
      "e_nummer": "",
      "benamning": "Kontakt 6 polig hane",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 35.64,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kontakt-6-polig-hane"
    },
    {
      "artikelnummer": "443552",
      "e_nummer": "",
      "benamning": "Kontakt 6 polig hona",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 31.75,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kontakt-6-polig-hona"
    },
    {
      "artikelnummer": "443875",
      "e_nummer": "",
      "benamning": "Kopplingsstift hane",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6.35,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kopplingsstift-hane"
    },
    {
      "artikelnummer": "443658",
      "e_nummer": "",
      "benamning": "Kopplingsstift hona",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 6.68,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/kopplingsstift-hona"
    },
    {
      "artikelnummer": "50091608",
      "e_nummer": "",
      "benamning": "L-konsol MEXL2",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 299.93,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/l-konsol-mexl2"
    },
    {
      "artikelnummer": "50002701",
      "e_nummer": "",
      "benamning": "Låshus Yale Doorman L3S",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1930.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/lashus-yale-doorman-l3s"
    },
    {
      "artikelnummer": "50140736",
      "e_nummer": "",
      "benamning": "Manöverpanel Danapad V3 silver",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1462.37,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/manoverpanel-danapad-v3-silver"
    },
    {
      "artikelnummer": "443611",
      "e_nummer": "",
      "benamning": "Mellanbricka till 580/582/8180/8181",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 63.7,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/mellanbricka-till-580-582-8180-8181"
    },
    {
      "artikelnummer": "50138775",
      "e_nummer": "",
      "benamning": "Monteringsstolpe 1805 plan vä",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1256.95,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-1805-plan-va"
    },
    {
      "artikelnummer": "50464324",
      "e_nummer": "",
      "benamning": "Monteringsstolpe 9028",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 696.17,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-9028"
    },
    {
      "artikelnummer": "50464280",
      "e_nummer": "",
      "benamning": "Monteringsstolpe 9036",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 696.17,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-9036"
    },
    {
      "artikelnummer": "LG-LGR-0054",
      "e_nummer": "",
      "benamning": "Monteringsstolpe 930-26",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 949.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-930-26"
    },
    {
      "artikelnummer": "50152544",
      "e_nummer": "",
      "benamning": "Monteringsstolpe 930E",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1042.31,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-930e"
    },
    {
      "artikelnummer": "50100824",
      "e_nummer": "",
      "benamning": "Monteringsstolpe 930T",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 790.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-930t"
    },
    {
      "artikelnummer": "50022944",
      "e_nummer": "",
      "benamning": "Monteringsstolpe S2-12",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 468.23,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-s2-12"
    },
    {
      "artikelnummer": "50114982",
      "e_nummer": "",
      "benamning": "Monteringsstolpe SA30V",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1002.75,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-sa30v"
    },
    {
      "artikelnummer": "50138698",
      "e_nummer": "",
      "benamning": "Monteringsstolpe SA32T",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 918.75,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-sa32t"
    },
    {
      "artikelnummer": "50108257",
      "e_nummer": "",
      "benamning": "Monteringsstolpe SA61/65",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 332.29,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-sa61-65"
    },
    {
      "artikelnummer": "50138685",
      "e_nummer": "",
      "benamning": "Monteringsstolpe SA70",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1060.5,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-sa70"
    },
    {
      "artikelnummer": "50151825",
      "e_nummer": "",
      "benamning": "Monteringsstolpe SA75",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1123.5,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-sa75"
    },
    {
      "artikelnummer": "50155009",
      "e_nummer": "",
      "benamning": "Monteringsstolpe SB07",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 488.25,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-sb07"
    },
    {
      "artikelnummer": "50463255",
      "e_nummer": "",
      "benamning": "Monteringsstolpe SC30TV-15",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 824.25,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-sc30tv-15"
    },
    {
      "artikelnummer": "50463243",
      "e_nummer": "",
      "benamning": "Monteringsstolpe SC80",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 987.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-sc80"
    },
    {
      "artikelnummer": "50463242",
      "e_nummer": "",
      "benamning": "Monteringsstolpe SC86",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1044.75,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-sc86"
    },
    {
      "artikelnummer": "50463240",
      "e_nummer": "",
      "benamning": "Monteringsstolpe SC87-15",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 645.75,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-sc87-15"
    },
    {
      "artikelnummer": "10013178",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST187b hö",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 829.13,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st187b-ho"
    },
    {
      "artikelnummer": "50111847",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST3502 vinklad",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 608.02,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st3502-vinklad"
    },
    {
      "artikelnummer": "50111856",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST3526V vinklad",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 935.25,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st3526v-vinklad"
    },
    {
      "artikelnummer": "50463402",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST4003-13 vinklad",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 893.24,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st4003-13-vinklad"
    },
    {
      "artikelnummer": "50093940",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST4003-15 vinklad",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 893.24,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st4003-15-vinklad"
    },
    {
      "artikelnummer": "50108236",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST4009-20 plan",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 718.58,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st4009-20-plan"
    },
    {
      "artikelnummer": "50108237",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST4009-21 plan",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 718.58,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st4009-21-plan"
    },
    {
      "artikelnummer": "50464321",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST4083 vinklad",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1177.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st4083-vinklad"
    },
    {
      "artikelnummer": "50001800",
      "e_nummer": "",
      "benamning": "Monteringsstolpe St4220",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1104.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st4220"
    },
    {
      "artikelnummer": "50025244",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST6504 vinklad hö",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 818.07,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st6504-vinklad-ho"
    },
    {
      "artikelnummer": "10020242",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST6509 Sapa 60",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1223.79,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st6509-sapa-60"
    },
    {
      "artikelnummer": "10023854",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST6516 vinklad",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1238.16,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st6516-vinklad"
    },
    {
      "artikelnummer": "10023855",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST6517 vinklad",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1238.16,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st6517-vinklad"
    },
    {
      "artikelnummer": "50025249",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST6559 plan",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 818.07,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st6559-plan"
    },
    {
      "artikelnummer": "50101095",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST6572",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1238.16,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st6572"
    },
    {
      "artikelnummer": "50101096",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST6574",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1196.15,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st6574"
    },
    {
      "artikelnummer": "50094143",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST9505V plan",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 981.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st9505v-plan"
    },
    {
      "artikelnummer": "50464392",
      "e_nummer": "",
      "benamning": "Monteringsstolpe ST9556 vinklad vänster",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 842.39,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-st9556-vinklad-vanster"
    },
    {
      "artikelnummer": "10009219",
      "e_nummer": "",
      "benamning": "Monteringsstolpe T109-U",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 541.6,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-t109-u"
    },
    {
      "artikelnummer": "10009233",
      "e_nummer": "",
      "benamning": "Monteringsstolpe T24",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 647.33,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-t24"
    },
    {
      "artikelnummer": "10009234",
      "e_nummer": "",
      "benamning": "Monteringsstolpe T44-12H",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 613.88,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/monteringsstolpe-t44-12h"
    },
    {
      "artikelnummer": "50111650",
      "e_nummer": "",
      "benamning": "Motorlås 840C-50 Hi-O kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17990.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-840c-50-hi-o-kpl"
    },
    {
      "artikelnummer": "50111652",
      "e_nummer": "",
      "benamning": "Motorlås 841C-50 Hi-O kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17990.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-841c-50-hi-o-kpl"
    },
    {
      "artikelnummer": "50100945",
      "e_nummer": "",
      "benamning": "Motorlås EL573 kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 14480.38,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-el573-kpl"
    },
    {
      "artikelnummer": "50091061",
      "e_nummer": "",
      "benamning": "Motorlås EL574 vä kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 23597.44,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-el574-va-kpl"
    },
    {
      "artikelnummer": "50091062",
      "e_nummer": "",
      "benamning": "Motorlås EL575 kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 23597.44,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-el575-kpl"
    },
    {
      "artikelnummer": "50142777",
      "e_nummer": "",
      "benamning": "Motorlås EL595 med anslutningskabel",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17844.28,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-el595-med-anslutningskabel"
    },
    {
      "artikelnummer": "10009970",
      "e_nummer": "",
      "benamning": "Motorlås EL648/25 kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17990.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-el648-25-kpl"
    },
    {
      "artikelnummer": "50025396",
      "e_nummer": "",
      "benamning": "Motorlås EL754 Hi-O  kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 25039.91,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-el754-hi-o-kpl"
    },
    {
      "artikelnummer": "50091067",
      "e_nummer": "",
      "benamning": "Motorlås EL874 hö kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 24471.83,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-el874-ho-kpl"
    },
    {
      "artikelnummer": "50091068",
      "e_nummer": "",
      "benamning": "Motorlås EL874 vä kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 24471.83,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-el874-va-kpl"
    },
    {
      "artikelnummer": "50091069",
      "e_nummer": "",
      "benamning": "Motorlås EL875 hö kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 24471.83,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-el875-ho-kpl"
    },
    {
      "artikelnummer": "50091070",
      "e_nummer": "",
      "benamning": "Motorlås EL875 vä kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 24471.83,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-el875-va-kpl"
    },
    {
      "artikelnummer": "50460162",
      "e_nummer": "",
      "benamning": "Motorlås Protector 909ML kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 11759.15,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-protector-909ml-kpl"
    },
    {
      "artikelnummer": "50460160",
      "e_nummer": "",
      "benamning": "Motorlås Protector 919ML höger kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 11759.15,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-protector-919ml-hoger-kpl"
    },
    {
      "artikelnummer": "50460168",
      "e_nummer": "",
      "benamning": "Motorlås Protector 919ML vänster",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10689.65,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-protector-919ml-vanster"
    },
    {
      "artikelnummer": "50000561",
      "e_nummer": "",
      "benamning": "Motorlås ST350",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10350.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-st350"
    },
    {
      "artikelnummer": "50000562",
      "e_nummer": "",
      "benamning": "Motorlås ST350 Kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 13346.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-st350-kpl"
    },
    {
      "artikelnummer": "50466181",
      "e_nummer": "",
      "benamning": "Motorlås ST350S",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10350.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-st350s"
    },
    {
      "artikelnummer": "50000567",
      "e_nummer": "",
      "benamning": "Motorlås ST352-L vänster",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 11385.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-st352-l-vanster"
    },
    {
      "artikelnummer": "50000563",
      "e_nummer": "",
      "benamning": "Motorlås ST352-L vänster Kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 14381.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-st352-l-vanster-kpl"
    },
    {
      "artikelnummer": "50000564",
      "e_nummer": "",
      "benamning": "Motorlås ST352-R höger",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 11385.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-st352-r-hoger"
    },
    {
      "artikelnummer": "50000569",
      "e_nummer": "",
      "benamning": "Motorlås ST352-R höger Kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 14381.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-st352-r-hoger-kpl"
    },
    {
      "artikelnummer": "50461979",
      "e_nummer": "",
      "benamning": "Motorlås ST535 kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 23569.26,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-st535-kpl"
    },
    {
      "artikelnummer": "50457511",
      "e_nummer": "",
      "benamning": "Motorlås ST550 kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 21688.8,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlas-st550-kpl"
    },
    {
      "artikelnummer": "50111651",
      "e_nummer": "",
      "benamning": "Motorlåshus 841C-50 Hi-O",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 12990.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-841c-50-hi-o"
    },
    {
      "artikelnummer": "50142775",
      "e_nummer": "",
      "benamning": "Motorlåshus EL495/29",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17404.3,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-el495-29"
    },
    {
      "artikelnummer": "50142825",
      "e_nummer": "",
      "benamning": "Motorlåshus EL574 hö",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 14296.59,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-el574-ho"
    },
    {
      "artikelnummer": "50091064",
      "e_nummer": "",
      "benamning": "Motorlåshus EL574 vä",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 14296.59,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-el574-va"
    },
    {
      "artikelnummer": "50091065",
      "e_nummer": "",
      "benamning": "Motorlåshus EL575",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 14296.59,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-el575"
    },
    {
      "artikelnummer": "440116",
      "e_nummer": "",
      "benamning": "Motorlåshus EL648/25 utan styrenhet",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17343.03,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-el648-25-utan-styrenhet"
    },
    {
      "artikelnummer": "50091095",
      "e_nummer": "",
      "benamning": "Motorlåshus EL754 Hi-O",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17883.26,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-el754-hi-o"
    },
    {
      "artikelnummer": "50091071",
      "e_nummer": "",
      "benamning": "Motorlåshus EL874 hö",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17705.04,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-el874-ho"
    },
    {
      "artikelnummer": "50091072",
      "e_nummer": "",
      "benamning": "Motorlåshus EL874 vä",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17705.04,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-el874-va"
    },
    {
      "artikelnummer": "50091073",
      "e_nummer": "",
      "benamning": "Motorlåshus EL875 höger",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17705.04,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-el875-ho"
    },
    {
      "artikelnummer": "50091074",
      "e_nummer": "",
      "benamning": "Motorlåshus EL875 vänster",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17705.04,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlashus-el875-va"
    },
    {
      "artikelnummer": "50111653",
      "e_nummer": "",
      "benamning": "Motorlåspaket 804C-50 HI-O",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 19710.02,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlaspaket-804c-50-hi-o"
    },
    {
      "artikelnummer": "50111654",
      "e_nummer": "",
      "benamning": "Motorlåspaket 814C-50 HI-O",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 19710.02,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorlaspaket-814c-50-hi-o"
    },
    {
      "artikelnummer": "50143010",
      "e_nummer": "",
      "benamning": "Motorslutbleck Compact",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10302.49,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorslutbleck-compact"
    },
    {
      "artikelnummer": "50131336",
      "e_nummer": "",
      "benamning": "Motorslutbleck Rapid",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 9881.11,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorslutbleck-rapid"
    },
    {
      "artikelnummer": "50131327",
      "e_nummer": "",
      "benamning": "Motorslutbleck Rapid kpl",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 19962.22,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorslutbleck-rapid-kpl"
    },
    {
      "artikelnummer": "50139503",
      "e_nummer": "",
      "benamning": "Motorvred Danalock V3 silver Zigbee",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 2959.45,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorvred-danalock-v3-silver-zigbee"
    },
    {
      "artikelnummer": "50150726",
      "e_nummer": "",
      "benamning": "Onelinebrygga Danabridge V3",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1226.22,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/onelinebrygga-danabridge-v3"
    },
    {
      "artikelnummer": "50457551",
      "e_nummer": "",
      "benamning": "Säkerhetsslutbleck ST9009-15",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 746.21,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/sakerhetsslutbleck-st9009-15"
    },
    {
      "artikelnummer": "8058332",
      "e_nummer": "",
      "benamning": "Skruv till elslutbleck M4x8",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 17.82,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/skruv-till-elslutbleck-m4x8"
    },
    {
      "artikelnummer": "50130485",
      "e_nummer": "",
      "benamning": "Slutbleck 106-4",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 687.75,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-106-4"
    },
    {
      "artikelnummer": "422605",
      "e_nummer": "",
      "benamning": "Slutbleck 4613",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 233.91,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-4613"
    },
    {
      "artikelnummer": "8041019",
      "e_nummer": "",
      "benamning": "Slutbleck 725",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 690.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-725"
    },
    {
      "artikelnummer": "50026131",
      "e_nummer": "",
      "benamning": "Slutbleck EA307 2.5MM",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 278.47,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-ea307-2-5mm"
    },
    {
      "artikelnummer": "10020256",
      "e_nummer": "",
      "benamning": "Slutbleck LP711 ställbart 12-16",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 473.4,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-lp711-stallbart-12-16"
    },
    {
      "artikelnummer": "50026135",
      "e_nummer": "",
      "benamning": "Slutbleck LP712 ställbart 12-16",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 450.78,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-lp712-stallbart-12-16"
    },
    {
      "artikelnummer": "50117949",
      "e_nummer": "",
      "benamning": "Slutbleck SB631/75",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 190.96,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-sb631-75"
    },
    {
      "artikelnummer": "50108255",
      "e_nummer": "",
      "benamning": "Slutbleck SB921/65",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 190.96,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-sb921-65"
    },
    {
      "artikelnummer": "50461473",
      "e_nummer": "",
      "benamning": "Slutbleck ST2009-12",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 268.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-st2009-12"
    },
    {
      "artikelnummer": "50101075",
      "e_nummer": "",
      "benamning": "Slutbleck ST4076",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 432.25,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-st4076"
    },
    {
      "artikelnummer": "50459615",
      "e_nummer": "",
      "benamning": "Slutbleck ST9014-27",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 746.21,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-st9014-27"
    },
    {
      "artikelnummer": "50000088",
      "e_nummer": "",
      "benamning": "Slutbleck ST9015",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 700.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/slutbleck-st9015"
    },
    {
      "artikelnummer": "50022191",
      "e_nummer": "",
      "benamning": "Splitpinnar EL580  57+50mm",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 228.34,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/splitpinnar-el580-57-50mm"
    },
    {
      "artikelnummer": "50022192",
      "e_nummer": "",
      "benamning": "Splitpinnar EL580  77+50mm",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 216.92,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/splitpinnar-el580-77-50mm"
    },
    {
      "artikelnummer": "50025809",
      "e_nummer": "",
      "benamning": "Splitpinnar EL580 120+120mm",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 435.53,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/splitpinnar-el580-120-120mm"
    },
    {
      "artikelnummer": "10011845",
      "e_nummer": "",
      "benamning": "Stolpe 580/582 osym",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 505.7,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/stolpe-580-582-osym"
    },
    {
      "artikelnummer": "50131335",
      "e_nummer": "",
      "benamning": "Styrenhet A1D",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 9859.72,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/styrenhet-a1d"
    },
    {
      "artikelnummer": "50091075",
      "e_nummer": "",
      "benamning": "Styrenhet EA453",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 10130.69,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/styrenhet-ea453"
    },
    {
      "artikelnummer": "50000087",
      "e_nummer": "",
      "benamning": "Styrenhet ST300C",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 2070.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/styrenhet-st300c"
    },
    {
      "artikelnummer": "50131489",
      "e_nummer": "",
      "benamning": "Systemkortsats",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 593.57,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/systemkortsats"
    },
    {
      "artikelnummer": "10014387",
      "e_nummer": "",
      "benamning": "Tillbehörspåse EL580/582",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 238.37,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/tillbehorspase-el580-582"
    },
    {
      "artikelnummer": "50001819",
      "e_nummer": "",
      "benamning": "Yale ConnectX Wi-Fi Bridge",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 799.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/yale-connect-wifi-brygga"
    },
    {
      "artikelnummer": "50001829",
      "e_nummer": "",
      "benamning": "Yale Linus L2 silver",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3790.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorvred-yale-linus-l2-silver"
    },
    {
      "artikelnummer": "50001830",
      "e_nummer": "",
      "benamning": "Yale Linus L2 svart",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 3790.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/motorvred-yale-linus-l2-svart"
    },
    {
      "artikelnummer": "50024091",
      "e_nummer": "",
      "benamning": "Z-Konsol MS 15",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 1953.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/z-konsol-ms-15"
    },
    {
      "artikelnummer": "50461903",
      "e_nummer": "",
      "benamning": "Zigbee modul Nimly kodlås",
      "lagsta_orderantal": null,
      "rabattgrupp": "E",
      "pris": 599.0,
      "supplier": "Låsgiganten",
      "url": "https://lasgiganten.se/products/zigbee-modul-nimly-kodlas"
    }
  ]
};
